### ISSUE TITLE
Request: Start an installed app like Amazon Video or Kodi

### ISSUE THREAD

**Issue by Pe-MaKer** [gerard33/home-assistant#5]
I'm wondering if it would be possible to start an App from within HA.
It would be cool to start for example the VLC media player on the TV showing the RTSP stream from the Babycam automatically.
Or if the preferred steaming App would be started whenever the living room enters the "Couch potato mode".

Maybe "setActiveApp" could help here:
https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/appcontrol/v1_0/setActiveApp/

**Comment by gerard33** [comment]
See my comment at #3 regarding the Android Debug Bridge addon. With that addon this is all possible.
